### ISSUE TITLE
Xml Extensions For Stream

### ISSUE THREAD

**Issue by hassancode** [KevinDockx/StreamExtensions#3]
I couldn't find any extension for XML, are these extensions similar for XML as well?

Another question, XmlTextReader directly takes Stream input, do we still need StreamReader as wrapper on top?

**Comment by KevinDockx** [comment]
I haven't created extensions for XML, but I'm open to PRs ;-)  If you're using XmlTextReader you can just use the stream as input, no need for an additional StreamReader.
