### ISSUE TITLE
CancellationToken for Async versions

### ISSUE THREAD

**Issue by sbrockway** [KevinDockx/StreamExtensions#4]
Would there be value in allowing an optional cancellation token to be passed for the SerializeToJsonAndWriteAsync() versions and then passing that to jsonTextWriter.FlushAsync()?

**Comment by KevinDockx** [comment]
Didn't realize FlushAsync accepts such a token - if it does, yes, that would definitley be a good idea.

**Comment by sbrockway** [comment]
I'll make a fork and submit a PR

**Comment by KevinDockx** [comment]
Merged, tnx!
