### ISSUE TITLE
Moving extensions directly to HttpResponseMessage class

### ISSUE THREAD

**Issue by klutch1991** [KevinDockx/StreamExtensions#9]
Hello, thanks a lot for the useful library provided.
Doesn't it make sense to provide extension methods like `ReadAndDeserializeFromJsonAsync()` directly to `HttpResponseMessage` class? Usage could be simplified to smth like:
```
using (var response = await httpClient.SendAsync(request))
{
    Person person = await response.DeserializeAsStreamAsync<Person>();
}
```

**Comment by KevinDockx** [comment]
That's a good idea :)  Would add them though, not replace the existing methods.  Would you be willing to provide a PR?  If not I'll just assign myself, no problem either.

**Comment by klutch1991** [comment]
Sure, will provide PR soon.

**Comment by klutch1991** [comment]
@KevinDockx, provided PR. Please, take a look. #10

**Comment by KevinDockx** [comment]
Thank you - will be part of the next release :)
